# .github/workflows/tmate-runner.yml

name: Tmate Parallel Runner (Recommended)

on:
  workflow_dispatch:

jobs:
  tmate-session:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_id: [1, 2, 3, 4, 5]
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup tmate session (Job ${{ matrix.job_id }})
        # This official action handles downloading, running, and waiting.
        # It will keep the job running until the timeout is reached or you disconnect.
        uses: tmate-io/tmate-action@v1
